### PR TITLE
Controller Edt interfacing with Schedule Facade

### PR DESCRIPTION
**Pull request by Desmondmies**
controller implemention using Facade and Observer Pattern

### CODE REVIEW

**Comment by Theo-Hafsaoui** [comment]
Not a great idead to start from PR, it might cause issue into the future

**Comment by Desmondmies** [comment]
i wasn't sure how to do, merging to your facade branch seemed to be the easiest way for me to continue working upon Schedule Facade without waiting merge into develop

**Comment by Theo-Hafsaoui** [comment]
I know and understand, that the main issue with our workflow. It's slow. but it would hypocrite of me to not say anything to you when I am quiet harsh with @anastygnome

**Comment by anastygnome** [comment]
@Desmondmies do you need help to fix the conflicts?

**Comment by Desmondmies** [comment]
image

Current interface look
(do not forget to execute db_populate2Weeks.sql, i'll share it on discord)

### Quick summary :
- Linked Controller / Facade (now displays weekly schedule for a student)
- Added Weeks Support & Controls
- Polished / Recolored interface

**Review by Theo-Hafsaoui — APPROVED** [review]

**Review by anastygnome — APPROVED** [review]
good work

**Pull request merged**
