### PR TITLE
update architecture

### PR DESCRIPTION
**Pull request by Theo-Hafsaoui**
I updated some inconsistency in the architecture of our package
_before_
```
.
├── pom.xml
└── src
    ├── main
    │   └── java
    │       └── fr
    │           └── univtln
    │               └── lhd
    │                   └── entitys
    │                       ├── Admin.java
    │                       ├── Guest.java
    │                       ├── Lecturer.java
    │                       ├── Schedule.java
    │                       ├── slots
    │                       │   ├── Classroom.java
    │                       │   ├── Group.java
    │                       │   ├── Slot.java
    │                       │   └── Subject.java
    │                       ├── Student.java
    │                       └── User.java
    └── test
        └── java
            └── fr
                └── univtln
                    └── lhd
                        ├── AppTest.java
                        └── entitys
                            ├── AdminTest.java
                            ├── LecturerTest.java
                            ├── slots
                            │   ├── ClassroomTest.java
                            │   ├── GroupTest.java
                            │   ├── SlotTest.java
                            │   └── SubjectTest.java
                            ├── StudentTest.java
                            └── UserTest.java

```
_After_
```
.
│   ├── pom.xml
│   ├── src
│   │   ├── main
│   │   │   └── java
│   │   │       └── fr
│   │   │           └── univtln
│   │   │               └── lhd
│   │   │                   └── model
│   │   │                       ├── dao
│   │   │                       │   ├── slot
│   │   │                       │   └── user
│   │   │                       └── entitys
│   │   │                           ├── Schedule.java
│   │   │                           ├── slots
│   │   │                           │   ├── Classroom.java
│   │   │                           │   ├── Group.java
│   │   │                           │   ├── Slot.java
│   │   │                           │   └── Subject.java
│   │   │                           └── user
│   │   │                               ├── Admin.java
│   │   │                               ├── Guest.java
│   │   │                               ├── Lecturer.java
│   │   │                               ├── Student.java
│   │   │                               └── User.java
│   │   └── test
│   │       └── java
│   │           └── fr
│   │               └── univtln
│   │                   └── lhd
│   │                       └── entitys
│   │                           ├── slots
│   │                           │   ├── ClassroomTest.java
│   │                           │   ├── GroupTest.java
│   │                           │   ├── SlotTest.java
│   │                           │   └── SubjectTest.java
│   │                           └── user
│   │                               ├── AdminTest.java
│   │                               ├── LecturerTest.java
│   │                               ├── StudentTest.java
│   │                               └── UserTest.java
```

### CODE REVIEW

**Review by Desmondmies — APPROVED** [review]
- [x] Nice

**Review by anastygnome — DISMISSED** [review]

**Comment by anastygnome** [comment]
Code smells are fixed. The coverage warning is to be discarded (lombok annotations-related) or fixed by @Theo-Hafsaoui (that's your thing I guess)

**Comment by Theo-Hafsaoui** [comment]
``@EqualsAndHashCode(callSuper = true)``
I saw the code smell, but didn't understand why it was necessary

**Comment by Theo-Hafsaoui** [comment]
by the way you should have squash after review

**Comment by anastygnome** [comment]
@Theo-Hafsaoui if one day we have a 

```java 
Admin a.equals(Admin b) 
```
with a and b having the exact same attributes (that would be a bug, but still ) but for their faculty, the comparison would return True (as it would call the super equals method.

Overriding is the way to go in those cases.

**Comment by Theo-Hafsaoui** [comment]
But that the comportment that I want, imagine an Admin of multiple faculty that is the same User

**Comment by anastygnome** [comment]
I wonder how you intended to have an admin manage sevral faculties with a String as its only attribute.   
You should use a Set/Collection  instead. 

Both issues would then be addressed.

**Comment by Theo-Hafsaoui** [comment]
That a strange behavior, I admit, and clearly not the intent of the `faculty` attribute. 
I just think that a `faculty` doesn't really _define_ an Admin, multiple instance of an Admin should be equal even if the the name of their faculty is different.
```
a.faculty=sciences
a.faculty=Sciences
Admin a.equals(Admin b) --> should be True
```
And not only for admin but for every User

A fix for admin could be an enum

**Comment by Theo-Hafsaoui** [comment]
Ok, resolve. For posterity it is better to explicitly underline our choice for `equal`
with an override of `equal` to avoid
```
User a = new admin(...)
User b = new admin(...)
a.faculty=sciences
b.faculty=Sciences
a.equals( b) --> True
---------------------------------
Admin a = new admin(...)
Admin b = new admin(...)
a.faculty=sciences
b.faculty=Sciences
a.equals( b) --> True
```

**Pull request merged**
