### PR TITLE
update lhd.sql and fix gitignore

### PR DESCRIPTION
**Pull request by anastygnome**
this PR adds the missing unique constraint on the emails, group names, subject names and emails across tables. 

Also update the gitignore due to intellij creating two directories in some instances.

### CODE REVIEW

**Comment by Theo-Hafsaoui** [comment]
210 ligne changed! we definitively consider changing to a script this is not pratical...

**Review by Theo-Hafsaoui — CHANGES_REQUESTED** [review]
Show the change the sql file is not readable

**Comment by Theo-Hafsaoui** [comment]
`` nb_heure_max double precision NOT NULL``
Errr #41

**Comment by anastygnome** [comment]
I've added unique constraint on the emails, group names, subject names and emails for all users, professors, admins 


table admins altered COLUMN id added generated always as identity
altered table subjects dropped COLUMN nb_heure_max
altered table subjects added constraint subject_unique UNIQUE(name);
same for student groups names

**Review by Theo-Hafsaoui — APPROVED** [review]
thank you for the change

**Review by Desmondmies — APPROVED** [review]
ok

**Pull request merged**
